// <auto-generated />
namespace EFCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddReqired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReqired));
        
        string IMigrationMetadata.Id
        {
            get { return "202504100111022_AddReqired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
